name: Despierta Streamlit

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: |
          curl -I https://lecturas-hes.streamlit.app/
          echo "Ping enviado con éxito"
